name: endless_runner
description: A WebView shell for loading web games.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.0
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.5
  appsflyer_sdk: ^6.14.2
  connectivity_plus: ^6.1.4
  http: ^1.2.2
  shared_preferences: ^2.2.2
  advertising_id: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true
